export const skills = {
  frontend: [
    'html',
    'css',
    'javascript',
    'typescript',
    'vue',
    'tailwind css',
    'sass',
    'babel',
    'webpack',
    'CORS',
    'Axios',
    'HTTP interception/transformation',
    'Localization/Internationalization',
    'pagination',
    'client-side storage mechanisms',
  ],
  backend: [
    'node js',
    'express js',
    'c#',
    '.net core',
    'C/C++',
    'pyhton',
    'java',
    'sql relational database',
    'no-sql database',
    'object relational mapping',
  ],
  other: ['bash', 'powershell', 'git', 'testing', 'docker'],
};
